### ISSUE TITLE
Sending attachments causes 400s

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#36]
Reproducible via chatbot.  See logs below.

```
2017-03-20T01:44:04.283997+00:00 app[web.1]: I, [2017-03-20T01:44:04.283910 #7]  INFO -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] Started POST "/api/v1/attachments?attachment_id=759&asset=https%3A%2F%2Fscontent.xx.fbcdn.net%2Fv%2Ft34.0-12%2F17392983_10101355122330791_1050377810_n.jpg%3F_nc_ad%3Dz-m%26oh%3Db90b3be93e1cf83001bb339b19f96685%26oe%3D58D1290A&write_key=1553dfb1fed95eecf4cfe2511bec1117" for 54.81.133.236 at 2017-03-20 01:44:04 +0000
2017-03-20T01:44:04.286123+00:00 app[web.1]: I, [2017-03-20T01:44:04.286059 #7]  INFO -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] Processing by API::V1::AttachmentsController#create as JSON
2017-03-20T01:44:04.286204+00:00 app[web.1]: I, [2017-03-20T01:44:04.286144 #7]  INFO -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c]   Parameters: {"attachment_id"=>"759", "asset"=>"https://scontent.xx.fbcdn.net/v/t34.0-12/17392983_10101355122330791_1050377810_n.jpg?_nc_ad=z-m&oh=b90b3be93e1cf83001bb339b19f96685&oe=58D1290A", "write_key"=>"1553dfb1fed95eecf4cfe2511bec1117"}
2017-03-20T01:44:04.288607+00:00 app[web.1]: D, [2017-03-20T01:44:04.288538 #7] DEBUG -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c]   APIKey Exists (1.2ms)  SELECT  1 AS one FROM "api_keys" WHERE "api_keys"."write_key" = $1 LIMIT $2  [["write_key", "1553dfb1fed95eecf4cfe2511bec1117"], ["LIMIT", 1]]
2017-03-20T01:44:04.305010+00:00 app[web.1]: D, [2017-03-20T01:44:04.304923 #7] DEBUG -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170320-7-w5jvm'
2017-03-20T01:44:04.320673+00:00 app[web.1]: W, [2017-03-20T01:44:04.320586 #7]  WARN -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] DRAGONFLY: setting magic attribute for width to nil in <Dragonfly Attachment uid=nil, app=:default> because got error Command failed ('identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170320-7-w5jvm') with exit status 1 and stderr identify.im6: no decode delegate for this image format `/tmp/dragonfly20170320-7-w5jvm' @ error/constitute.c/ReadImage/544.
2017-03-20T01:44:04.320675+00:00 app[web.1]: 
2017-03-20T01:44:04.320916+00:00 app[web.1]: D, [2017-03-20T01:44:04.320864 #7] DEBUG -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170320-7-w5jvm'
2017-03-20T01:44:04.330126+00:00 app[web.1]: W, [2017-03-20T01:44:04.330044 #7]  WARN -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] DRAGONFLY: setting magic attribute for height to nil in <Dragonfly Attachment uid=nil, app=:default> because got error Command failed ('identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170320-7-w5jvm') with exit status 1 and stderr identify.im6: no decode delegate for this image format `/tmp/dragonfly20170320-7-w5jvm' @ error/constitute.c/ReadImage/544.
2017-03-20T01:44:04.330128+00:00 app[web.1]: 
2017-03-20T01:44:04.332082+00:00 app[web.1]: D, [2017-03-20T01:44:04.332020 #7] DEBUG -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c]    (1.2ms)  BEGIN
2017-03-20T01:44:04.335158+00:00 app[web.1]: D, [2017-03-20T01:44:04.335089 #7] DEBUG -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c]    (1.1ms)  ROLLBACK
2017-03-20T01:44:04.337733+00:00 app[web.1]: I, [2017-03-20T01:44:04.337653 #7]  INFO -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.15ms)
2017-03-20T01:44:04.337954+00:00 app[web.1]: I, [2017-03-20T01:44:04.337902 #7]  INFO -- : [c4f62c79-93e8-433e-b245-57fd9ce7079c] Completed 400 Bad Request in 52ms (Views: 2.1ms | ActiveRecord: 5.8ms)
2017-03-20T01:44:04.358092+00:00 heroku[router]: at=info method=POST path="/api/v1/attachments?attachment_id=759&asset=https%3A%2F%2Fscontent.xx.fbcdn.net%2Fv%2Ft34.0-12%2F17392983_10101355122330791_1050377810_n.jpg%3F_nc_ad%3Dz-m%26oh%3Db90b3be93e1cf83001bb339b19f96685%26oe%3D58D1290A&write_key=1553dfb1fed95eecf4cfe2511bec1117" host=www.raheem.ai request_id=c4f62c79-93e8-433e-b245-57fd9ce7079c fwd="54.81.133.236" dyno=web.1 connect=0ms service=57ms status=400 bytes=424 protocol=https
```

**Comment by kidbombay** [comment]
Closing as we expect asset to be a file, not a url.
Added feature already to support asset_url.

**Comment by jhankin** [comment]
Using the `asset_url` parameter doesn't appear to work:

```
2017-03-21T00:47:46.413153+00:00 app[web.1]: I, [2017-03-21T00:47:46.413086 #9]  INFO -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222] Started POST "/api/v1/attachments?attachment_id=767&asset_url=https%3A%2F%2Fscontent.xx.fbcdn.net%2Fv%2Ft34.0-12%2F17410140_10101355972512021_1465236599_n.jpg%3F_nc_ad%3Dz-m%26oh%3D9d65ab8d3db52de9b61afae477b4e7fd%26oe%3D58D3B092&write_key=1553dfb1fed95eecf4cfe2511bec1117" for 54.205.57.73 at 2017-03-21 00:47:46 +0000
2017-03-21T00:47:46.414803+00:00 app[web.1]: I, [2017-03-21T00:47:46.414755 #9]  INFO -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222] Processing by API::V1::AttachmentsController#create as JSON
2017-03-21T00:47:46.414855+00:00 app[web.1]: I, [2017-03-21T00:47:46.414817 #9]  INFO -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222]   Parameters: {"attachment_id"=>"767", "asset_url"=>"https://scontent.xx.fbcdn.net/v/t34.0-12/17410140_10101355972512021_1465236599_n.jpg?_nc_ad=z-m&oh=9d65ab8d3db52de9b61afae477b4e7fd&oe=58D3B092", "write_key"=>"1553dfb1fed95eecf4cfe2511bec1117"}
2017-03-21T00:47:46.417545+00:00 app[web.1]: D, [2017-03-21T00:47:46.417482 #9] DEBUG -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222]   APIKey Exists (1.7ms)  SELECT  1 AS one FROM "api_keys" WHERE "api_keys"."write_key" = $1 LIMIT $2  [["write_key", "1553dfb1fed95eecf4cfe2511bec1117"], ["LIMIT", 1]]
2017-03-21T00:47:46.508341+00:00 app[web.1]: D, [2017-03-21T00:47:46.508252 #9] DEBUG -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170321-9-1uq88we.jpg'
2017-03-21T00:47:46.520120+00:00 app[web.1]: D, [2017-03-21T00:47:46.520029 #9] DEBUG -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222]    (1.4ms)  BEGIN
2017-03-21T00:47:46.522919+00:00 app[web.1]: D, [2017-03-21T00:47:46.522856 #9] DEBUG -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222]    (1.3ms)  ROLLBACK
2017-03-21T00:47:46.525797+00:00 app[web.1]: I, [2017-03-21T00:47:46.525742 #9]  INFO -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.12ms)
2017-03-21T00:47:46.526026+00:00 app[web.1]: I, [2017-03-21T00:47:46.525977 #9]  INFO -- : [f011cbfd-2168-4a3f-8203-bd7e8e224222] Completed 400 Bad Request in 111ms (Views: 2.4ms | ActiveRecord: 4.4ms)
2017-03-21T00:47:46.525889+00:00 heroku[router]: at=info method=POST path="/api/v1/attachments?attachment_id=767&asset_url=https%3A%2F%2Fscontent.xx.fbcdn.net%2Fv%2Ft34.0-12%2F17410140_10101355972512021_1465236599_n.jpg%3F_nc_ad%3Dz-m%26oh%3D9d65ab8d3db52de9b61afae477b4e7fd%26oe%3D58D3B092&write_key=1553dfb1fed95eecf4cfe2511bec1117" host=www.raheem.ai request_id=f011cbfd-2168-4a3f-8203-bd7e8e224222 fwd="54.205.57.73" dyno=web.1 connect=1ms service=116ms status=400 bytes=424 protocol=https
```

**Comment by kidbombay** [comment]
@jhankin can you send me this image directly (not in github as it transforms the image)
fire@kidbombay.com

**Comment by kidbombay** [comment]
In attachments spec
using both
https://scontent.xx.fbcdn.net/v/t34.0-12/17410140_10101355972512021_1465236599_n.jpg?_nc_ad=z-m&oh=9d65ab8d3db52de9b61afae477b4e7fd&oe=58D3B092
http://www.joehankin.com/snowglobe/rubber_duck.jpg
causes the test to pass.
Going to try to do a curl request as same

**Comment by kidbombay** [comment]
The post to attachments spec works fine
http://staging.raheem.ai/api/v1/attachments?write_key=e6a92df490fec7da859f847d864ffdc7&incident_id=1&asset_url=http://www.joehankin.com/snowglobe/rubber_duck.jpg

Which creates an attachment here
http://staging.raheem.ai/incidents/Ebjz3zTc

You can view the result in the api
http://staging.raheem.ai/api/v1/incidents/1?write_key=e6a92df490fec7da859f847d864ffdc7

@Jlawlzz @Jlawlzz @BrandonAnderson 
It's something in how we are sending the asset_url from the bot but I'm not sure what.

**Comment by kidbombay** [comment]
http://staging.raheem.ai/api/v1/attachments?write_key=e6a92df490fec7da859f847d864ffdc7&incident_id=1&asset_url=https://scontent.xx.fbcdn.net/v/t34.0-12/17410140_10101355972512021_1465236599_n.jpg?_nc_ad=z-m%26oh=9d65ab8d3db52de9b61afae477b4e7fd%26oe=58D3B092

using the sent asset url from FB works fine too
http://staging.raheem.ai/api/v1/incidents/1?write_key=e6a92df490fec7da859f847d864ffdc7

**Comment by kidbombay** [comment]
Logs
```
2017-03-21T16:09:10.761288+00:00 app[web.1]: I, [2017-03-21T16:09:10.761215 #11]  INFO -- : [589f5602-49c6-44c3-8476-f12deb30a0c9] Started POST "/api/v1/attachments?write_key=[FILTERED]&incident_id=1&asset_url=https://scontent.xx.fbcdn.net/v/t34.0-12/17410140_10101355972512021_1465236599_n.jpg?_nc_ad=z-m%26oh=9d65ab8d3db52de9b61afae477b4e7fd%26oe=58D3B092" for 76.14.41.207 at 2017-03-21 16:09:10 +0000
2017-03-21T16:09:10.762388+00:00 app[web.1]: I, [2017-03-21T16:09:10.762326 #11]  INFO -- : [589f5602-49c6-44c3-8476-f12deb30a0c9] Processing by API::V1::AttachmentsController#create as JSON
2017-03-21T16:09:10.762433+00:00 app[web.1]: I, [2017-03-21T16:09:10.762389 #11]  INFO -- : [589f5602-49c6-44c3-8476-f12deb30a0c9]   Parameters: {"write_key"=>"[FILTERED]", "incident_id"=>"1", "asset_url"=>"https://scontent.xx.fbcdn.net/v/t34.0-12/17410140_10101355972512021_1465236599_n.jpg?_nc_ad=z-m&oh=9d65ab8d3db52de9b61afae477b4e7fd&oe=58D3B092"}
2017-03-21T16:09:10.764116+00:00 app[web.1]: D, [2017-03-21T16:09:10.764066 #11] DEBUG -- : [589f5602-49c6-44c3-8476-f12deb30a0c9]   APIKey Exists (0.6ms)  SELECT  1 AS one FROM "api_keys" WHERE "api_keys"."write_key" = $1 LIMIT $2  [["write_key", "e6a92df490fec7da859f847d864ffdc7"], ["LIMIT", 1]]
2017-03-21T16:09:10.803810+00:00 app[web.1]: D, [2017-03-21T16:09:10.803728 #11] DEBUG -- : [589f5602-49c6-44c3-8476-f12deb30a0c9] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170321-11-4gdr2c.jpg'
2017-03-21T16:09:10.814931+00:00 app[web.1]: D, [2017-03-21T16:09:10.814847 #11] DEBUG -- : [589f5602-49c6-44c3-8476-f12deb30a0c9]    (0.6ms)  BEGIN
2017-03-21T16:09:10.817442+00:00 app[web.1]: D, [2017-03-21T16:09:10.817370 #11] DEBUG -- : [589f5602-49c6-44c3-8476-f12deb30a0c9]   Incident Load (0.8ms)  SELECT  "incidents".* FROM "incidents" WHERE "incidents"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
2017-03-21T16:09:11.058827+00:00 heroku[router]: at=info method=POST path="/api/v1/attachments?write_key=e6a92df490fec7da859f847d864ffdc7&incident_id=1&asset_url=https://scontent.xx.fbcdn.net/v/t34.0-12/17410140_10101355972512021_1465236599_n.jpg?_nc_ad=z-m%26oh=9d65ab8d3db52de9b61afae477b4e7fd%26oe=58D3B092" host=staging.raheem.ai request_id=589f5602-49c6-44c3-8476-f12deb30a0c9 fwd="76.14.41.207" dyno=web.1 connect=1ms service=278ms status=200 bytes=771 protocol=http
2017-03-21T16:09:11.033919+00:00 app[web.1]: D, [2017-03-21T16:09:11.033840 #11] DEBUG -- : [589f5602-49c6-44c3-8476-f12deb30a0c9]   SQL (1.0ms)  INSERT INTO "attachments" ("incident_id", "asset_uid", "asset_name", "asset_width", "asset_height", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["incident_id", 1], ["asset_uid", "o7arulvszkrpi258ya03.jpg"], ["asset_name", "17410140_10101355972512021_1465236599_n.jpg"], ["asset_width", 360], ["asset_height", 640], ["created_at", 2017-03-21 16:09:11 UTC], ["updated_at", 2017-03-21 16:09:11 UTC]]
2017-03-21T16:09:11.035485+00:00 app[web.1]: D, [2017-03-21T16:09:11.035433 #11] DEBUG -- : [589f5602-49c6-44c3-8476-f12deb30a0c9]    (1.3ms)  COMMIT
2017-03-21T16:09:11.036979+00:00 app[web.1]: I, [2017-03-21T16:09:11.036905 #11]  INFO -- : [589f5602-49c6-44c3-8476-f12deb30a0c9] [active_model_serializers] Rendered AttachmentSerializer with ActiveModelSerializers::Adapter::Json (0.65ms)
2017-03-21T16:09:11.037219+00:00 app[web.1]: I, [2017-03-21T16:09:11.037160 #11]  INFO -- : [589f5602-49c6-44c3-8476-f12deb30a0c9] Completed 200 OK in 275ms (Views: 1.5ms | ActiveRecord: 4.3ms)
```

**Comment by jhankin** [comment]
UPDATE:

Looks like sending still images now works from an API perspective:

```
2017-03-26T21:20:07.905173+00:00 heroku[router]: at=info method=POST path="/api/v1/attachments?incident_id=813&asset_url=https%3A%2F%2Fscontent.xx.fbcdn.net%2Fv%2Ft34.0-12%2F17555505_10101361529505761_792095284_n.jpg%3F_nc_ad%3Dz-m%26oh%3D04f29d41e5625acf6da484c5913b1933%26oe%3D58DAEBEC&write_key=1553dfb1fed95eecf4cfe2511bec1117" host=www.raheem.ai request_id=6a69b04a-e5b4-4ad6-b677-ee50b88581be fwd="54.159.46.36" dyno=web.1 connect=4ms service=480ms status=200 bytes=767 protocol=https
2017-03-26T21:20:07.898223+00:00 app[web.1]: D, [2017-03-26T21:20:07.898138 #7] DEBUG -- : [6a69b04a-e5b4-4ad6-b677-ee50b88581be]   SQL (2.0ms)  INSERT INTO "attachments" ("incident_id", "asset_uid", "asset_name", "asset_width", "asset_height", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["incident_id", 813], ["asset_uid", "n1aep4xuiwelprqspwxa.jpg"], ["asset_name", "17555505_10101361529505761_792095284_n.jpg"], ["asset_width", 480], ["asset_height", 640], ["created_at", 2017-03-26 21:20:07 UTC], ["updated_at", 2017-03-26 21:20:07 UTC]]
2017-03-26T21:20:07.900913+00:00 app[web.1]: D, [2017-03-26T21:20:07.900763 #7] DEBUG -- : [6a69b04a-e5b4-4ad6-b677-ee50b88581be]    (2.4ms)  COMMIT
2017-03-26T21:20:07.902169+00:00 app[web.1]: I, [2017-03-26T21:20:07.902100 #7]  INFO -- : [6a69b04a-e5b4-4ad6-b677-ee50b88581be] [active_model_serializers] Rendered AttachmentSerializer with ActiveModelSerializers::Adapter::Json (0.57ms)
2017-03-26T21:20:07.902385+00:00 app[web.1]: I, [2017-03-26T21:20:07.902333 #7]  INFO -- : [6a69b04a-e5b4-4ad6-b677-ee50b88581be] Completed 200 OK in 473ms (Views: 1.3ms | ActiveRecord: 9.0ms)
```

This call successfully created http://raheem.ai/admin/attachment/5 but either the image data itself wasn't written properly or the internal asset URI is wrong, because the link to the image is broken.

**Comment by jhankin** [comment]
Meanwhile sending video still causes similar problems:

```
2017-03-26T21:18:24.487973+00:00 app[web.1]: I, [2017-03-26T21:18:24.487919 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] Started POST "/api/v1/attachments?incident_id=813&asset_url=https%3A%2F%2Fvideo.xx.fbcdn.net%2Fv%2Ft42.3356-2%2F17590350_10101361528133511_4008746101254389760_n.mp4%2Fvideo-1490563103.mp4%3Fvabr%3D492977%26oh%3Df379d4a6b8ba3dd0dc1b389dd048ee0c%26oe%3D58DA0590&write_key=[FILTERED]" for 54.159.46.36 at 2017-03-26 21:18:24 +0000
2017-03-26T21:18:24.489051+00:00 app[web.1]: I, [2017-03-26T21:18:24.488999 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] Processing by API::V1::AttachmentsController#create as JSON
2017-03-26T21:18:24.489053+00:00 app[web.1]: D, [2017-03-26T21:18:24.489005 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda]   Role Load (1.8ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = $1 AND "roles"."resource_type" IS NULL AND "roles"."resource_id" IS NULL ORDER BY "roles"."id" ASC LIMIT $2  [["name", "normal"], ["LIMIT", 1]]
2017-03-26T21:18:24.489101+00:00 app[web.1]: I, [2017-03-26T21:18:24.489061 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   Parameters: {"incident_id"=>"813", "asset_url"=>"https://video.xx.fbcdn.net/v/t42.3356-2/17590350_10101361528133511_4008746101254389760_n.mp4/video-1490563103.mp4?vabr=492977&oh=f379d4a6b8ba3dd0dc1b389dd048ee0c&oe=58DA0590", "write_key"=>"[FILTERED]"}
2017-03-26T21:18:24.491689+00:00 app[web.1]: D, [2017-03-26T21:18:24.491639 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   APIKey Exists (1.5ms)  SELECT  1 AS one FROM "api_keys" WHERE "api_keys"."write_key" = $1 LIMIT $2  [["write_key", "1553dfb1fed95eecf4cfe2511bec1117"], ["LIMIT", 1]]
2017-03-26T21:18:24.492609+00:00 app[web.1]: D, [2017-03-26T21:18:24.492559 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda]   Role Exists (1.8ms)  SELECT  1 AS one FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND "roles"."id" = $2 LIMIT $3  [["user_id", 192], ["id", 1], ["LIMIT", 1]]
2017-03-26T21:18:24.504970+00:00 app[web.1]: D, [2017-03-26T21:18:24.504910 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda]    (1.6ms)  COMMIT
2017-03-26T21:18:24.509305+00:00 app[web.1]: D, [2017-03-26T21:18:24.509249 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] [active_model_serializers]   Attachment Load (1.7ms)  SELECT "attachments".* FROM "attachments" WHERE "attachments"."incident_id" = $1  [["incident_id", 813]]
2017-03-26T21:18:24.514677+00:00 app[web.1]: D, [2017-03-26T21:18:24.514621 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] [active_model_serializers]   Officer Load (1.9ms)  SELECT "officers".* FROM "officers" WHERE "officers"."incident_id" = $1  [["incident_id", 813]]
2017-03-26T21:18:24.515345+00:00 app[web.1]: I, [2017-03-26T21:18:24.515295 #7]  INFO -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] [active_model_serializers] Rendered IncidentSerializer with ActiveModelSerializers::Adapter::Json (9.75ms)
2017-03-26T21:18:24.515546+00:00 app[web.1]: I, [2017-03-26T21:18:24.515501 #7]  INFO -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] Completed 200 OK in 50ms (Views: 6.8ms | ActiveRecord: 21.1ms)
2017-03-26T21:18:24.640108+00:00 app[web.1]: D, [2017-03-26T21:18:24.640032 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4'
2017-03-26T21:18:24.660122+00:00 app[web.1]: W, [2017-03-26T21:18:24.660048 #11]  WARN -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: setting magic attribute for width to nil in <Dragonfly Attachment uid=nil, app=:default> because got error Command failed ('identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4') with exit status 1 and stderr identify.im6: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1065.
2017-03-26T21:18:24.660124+00:00 app[web.1]: identify.im6: unable to open image `/tmp/magick-VGW80hgM.pam': No such file or directory @ error/blob.c/OpenBlob/2641.
2017-03-26T21:18:24.660125+00:00 app[web.1]: 
2017-03-26T21:18:24.660289+00:00 app[web.1]: D, [2017-03-26T21:18:24.660240 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4'
2017-03-26T21:18:24.535787+00:00 heroku[router]: at=info method=PATCH path="/api/v1/incidents/813?user_id=192&write_key=1553dfb1fed95eecf4cfe2511bec1117&incident_type_name=citation&start_time=1490400000&rating=1&description=I%20felt%20like%20a%20pool%20of%20cold%20water%20with%20one%20leaf%20floating%20in%20it&latitude=37.748345656973&longitude=-122.17693612467&metadata=%7B%22DATE_OF_INCIDENT%22%3A1490400000%2C%22TIME_OF_INCIDENT%22%3A%225pm%22%2C%22ENCOUNTER_LOCATION%22%3A%22%7B%5C%22lat%5C%22%3A37.748345656973%2C%5C%22long%5C%22%3A-122.17693612467%7D%22%2C%22CONTACT_OUTCOME%22%3A%22citation%22%2C%22CASE_NUMBER%22%3A%229462%22%2C%22INITIAL_CONTACT%22%3A%22got%20stopped%20on%20foot%22%2C%22POLICE_ACTION%22%3A%22other%22%2C%22POLICE_SEARCH%3F%22%3A%22yes%22%2C%22PERMISSION_TO_SEARCH%3F%22%3A%22no%22%2C%22NUMBER_OF_OFFICERS%22%3A%224%22%2C%22OFFICER_NAME%22%3A%22Hambone%20McGillicutty%22%2C%22OFFICER_BADGE_NUMBER%22%3A%226789%22%2C%22OFFICER_RACE%22%3A%22white%2Fcaucasian%22%2C%22OFFICER_GENDER%22%3A%22man%22%2C%22OFFICER_AGE%22%3A%2241-50%22%2C%22OFFICER_DETAILS_DESCRIPTION%22%3A%229%20feet%20tall%2C%20mouth%20full%20of%20corned%20beef%22%2C%22ENCOUNTER_SENTIMENT%22%3A%221%22%2C%22FURTHER_DESCRIPTION%22%3A%22I%20felt%20like%20a%20pool%20of%20cold%20water%20with%20one%20leaf%20floating%20in%20it%22%2C%22USER_REACTION%22%3A%22embarrassed%22%2C%22OFFICER_DISPOSITION%22%3A%22discriminatory%22%7D&reactions_list%5B0%5D=embarrassed&reactions_list%5B1%5D=discriminatory&tags_list%5B0%5D=citation" host=www.raheem.ai request_id=5000f273-fc81-4f6b-8e4b-07cc7460dcda fwd="54.159.46.36" dyno=web.1 connect=1ms service=56ms status=200 bytes=2271 protocol=https
2017-03-26T21:18:24.667315+00:00 app[web.1]: W, [2017-03-26T21:18:24.667260 #11]  WARN -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: setting magic attribute for height to nil in <Dragonfly Attachment uid=nil, app=:default> because got error Command failed ('identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4') with exit status 1 and stderr identify.im6: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1065.
2017-03-26T21:18:24.667325+00:00 app[web.1]: identify.im6: unable to open image `/tmp/magick-JtzxxIiQ.pam': No such file or directory @ error/blob.c/OpenBlob/2641.
2017-03-26T21:18:24.667325+00:00 app[web.1]: 
2017-03-26T21:18:24.669410+00:00 app[web.1]: D, [2017-03-26T21:18:24.669360 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]    (1.5ms)  BEGIN
2017-03-26T21:18:24.672495+00:00 app[web.1]: D, [2017-03-26T21:18:24.672445 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   Incident Load (1.8ms)  SELECT  "incidents".* FROM "incidents" WHERE "incidents"."id" = $1 LIMIT $2  [["id", 813], ["LIMIT", 1]]
2017-03-26T21:18:24.740125+00:00 app[web.1]: D, [2017-03-26T21:18:24.740054 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]    (1.4ms)  ROLLBACK
2017-03-26T21:18:24.740365+00:00 app[web.1]: I, [2017-03-26T21:18:24.740319 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] Completed 500 Internal Server Error in 251ms (ActiveRecord: 6.2ms)
2017-03-26T21:18:24.740459+00:00 app[web.1]: D, [2017-03-26T21:18:24.740418 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Reporting exception: Invalid image file
2017-03-26T21:18:24.768842+00:00 app[web.1]: I, [2017-03-26T21:18:24.768780 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Scheduling item
2017-03-26T21:18:24.768874+00:00 app[web.1]: I, [2017-03-26T21:18:24.768838 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Sending item
2017-03-26T21:18:25.148719+00:00 heroku[router]: at=info method=POST path="/api/v1/attachments?incident_id=813&asset_url=https%3A%2F%2Fvideo.xx.fbcdn.net%2Fv%2Ft42.3356-2%2F17590350_10101361528133511_4008746101254389760_n.mp4%2Fvideo-1490563103.mp4%3Fvabr%3D492977%26oh%3Df379d4a6b8ba3dd0dc1b389dd048ee0c%26oe%3D58DA0590&write_key=1553dfb1fed95eecf4cfe2511bec1117" host=www.raheem.ai request_id=31e84a1e-67ac-4928-94e1-b8ac71f5fa0a fwd="54.159.46.36" dyno=web.1 connect=1ms service=662ms status=500 bytes=243 protocol=https
2017-03-26T21:18:25.144861+00:00 app[web.1]: W, [2017-03-26T21:18:25.144765 #11]  WARN -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Got unexpected status code from Rollbar api: 429
2017-03-26T21:18:25.144913+00:00 app[web.1]: I, [2017-03-26T21:18:25.144851 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Response: {
2017-03-26T21:18:25.144914+00:00 app[web.1]:   "err": 1,
2017-03-26T21:18:25.144915+00:00 app[web.1]:   "message": "Over plan monthly limit. Project id 89859 access token f9cb01305bcf49e4bf4fc42d0ca39338."
2017-03-26T21:18:25.144915+00:00 app[web.1]: }
2017-03-26T21:18:25.144968+00:00 app[web.1]: I, [2017-03-26T21:18:25.144927 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=6c76efac-9f30-4921-8c13-ece1b32289eb (only available if report was successful)
2017-03-26T21:18:25.145023+00:00 app[web.1]: D, [2017-03-26T21:18:25.144983 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Exception uuid saved in env: 6c76efac-9f30-4921-8c13-ece1b32289eb
2017-03-26T21:18:25.145800+00:00 app[web.1]: F, [2017-03-26T21:18:25.145753 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   
2017-03-26T21:18:25.145840+00:00 app[web.1]: F, [2017-03-26T21:18:25.145802 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] CloudinaryException (Invalid image file):
2017-03-26T21:18:25.145874+00:00 app[web.1]: F, [2017-03-26T21:18:25.145839 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   
2017-03-26T21:18:25.145938+00:00 app[web.1]: F, [2017-03-26T21:18:25.145878 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] app/models/cloudinary_store.rb:5:in `write'
2017-03-26T21:18:25.145972+00:00 app[web.1]: F, [2017-03-26T21:18:25.145936 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] app/controllers/api/v1/attachments_controller.rb:5:in `create'
```

**Comment by jhankin** [comment]
I'm gonna close this issue and open two new ones since these are clearly separate problems.
